/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pwr.sim;

public class App {
    public static void main(String[] args) {
        World world = new World(50, 10);
        world.draw();
    }
}
