/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pwr.sim;

public class App {
    public static void main(String[] args) {
        int a = 2;
        String b = Integer.toString(a);
        System.out.println(b);
    }
}
